const listingMoviesData = [
  {
    id: 1,
    genre: "action",
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 7.5,
    genre: "action",
    posterImage: "/list-10.png",
  },
  {
    id: 2,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 8.2,
    genre: "action",
    posterImage: "/list-9.jpg",
  },
  {
    id: 3,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 6.9,
    genre: "action",
    posterImage: "/list-3.jpg",
  },
  {
    id: 4,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 7.8,
    genre: "action",
    posterImage: "/list-4.jpg",
  },
  {
    id: 5,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 6.5,
    genre: "action",
    posterImage: "/list-6.jpg",
  },
  {
    id: 6,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 8.0,
    genre: "action",
    posterImage: "/list-7.jpg",
  },
  {
    id: 7,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 7.2,
    genre: "action",
    posterImage: "/list-8.jpg",
  },
  {
    id: 8,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 6.8,
    genre: "action",
    posterImage: "/list-9.jpg",
  },
  {
    id: 9,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 7.9,
    genre: "action",
    posterImage: "/list-10.png",
  },
  {
    id: 10,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 8.5,
    genre: "action",
    posterImage: "/list-11.png",
  },
  {
    id: 11,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 7.3,
    genre: "action",
    posterImage: "/list-12.png",
  },
  {
    id: 12,
    description: "Movie Title",
    movieName: "Movie Title",
    rating: 8.0,
    genre: "action",
    posterImage: "/list-7.jpg",
  },
];

export default listingMoviesData;
